// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMl8UBfSl4Zyyo6XjemPbYxCABAvdalCc',
    appId: '1:380136097192:web:f3813bc9c2028c1462099d',
    messagingSenderId: '380136097192',
    projectId: 'park-now-fe8c4',
    authDomain: 'park-now-fe8c4.firebaseapp.com',
    databaseURL: 'https://park-now-fe8c4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'park-now-fe8c4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0q5pt_zuzdf6k4EKjD57WERsLhcG5THs',
    appId: '1:380136097192:android:c6c02906fd7161bb62099d',
    messagingSenderId: '380136097192',
    projectId: 'park-now-fe8c4',
    databaseURL: 'https://park-now-fe8c4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'park-now-fe8c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkHrUM9CaH0Qf2LGdKs2Gxx8c-461JLKE',
    appId: '1:380136097192:ios:55cea71b8a04c30162099d',
    messagingSenderId: '380136097192',
    projectId: 'park-now-fe8c4',
    databaseURL: 'https://park-now-fe8c4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'park-now-fe8c4.appspot.com',
    iosBundleId: 'com.example.park',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkHrUM9CaH0Qf2LGdKs2Gxx8c-461JLKE',
    appId: '1:380136097192:ios:55cea71b8a04c30162099d',
    messagingSenderId: '380136097192',
    projectId: 'park-now-fe8c4',
    databaseURL: 'https://park-now-fe8c4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'park-now-fe8c4.appspot.com',
    iosBundleId: 'com.example.park',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMl8UBfSl4Zyyo6XjemPbYxCABAvdalCc',
    appId: '1:380136097192:web:ca77927e8873aa4562099d',
    messagingSenderId: '380136097192',
    projectId: 'park-now-fe8c4',
    authDomain: 'park-now-fe8c4.firebaseapp.com',
    databaseURL: 'https://park-now-fe8c4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'park-now-fe8c4.appspot.com',
  );
}
